### ISSUE TITLE
[feature request] YT Vanced Venom Dark Mode Theme

### ISSUE THREAD

**Issue by Emulatorer** [X1nto/iYTBP-Vanced-Black-MAGISK#1]
Is it possible?

**Comment by X1nto** [comment]
Hi, unfortunately the apk files itself are not mine, I can't really modify them is I'm a total noob in using ApkTool, even if i would, I'll have to ask permissions to Vanced Team for modifying and distributing their apks such way.

As of now I'm gonna close this issue but who knows, maybe I'll make variations of splash screens ;)
